# Read the Docs configuration file (see https://docs.readthedocs.io/en/stable/config-file/v2.html
# for details).

version: 2

sphinx:
   configuration: conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

  # https://github.com/readthedocs/readthedocs.org/issues/4912#issuecomment-1143587902s
  jobs:
    post_install:
      - pip install poetry==1.7.1  # match version from poetry.lock
      - poetry config virtualenvs.create false
      - poetry install --all-extras
