= python-testcontainers

python-testcontainers provides capabilities to spin up a docker containers for test purposes would that be a database, Selenium web browser or any other cotainer.

Currently available features:

- Selenium Grid containers
- Selenim Standalone containers
- MySql db container
- PostgreSQL db container

Usage example:

=== Selenium Standalone containers

You can execute test scripts using Standalone Selenium Docker containers for Firefox and Chrome:

[source,python]
----
    def test_standalone_container(self):
        chrome = StandaloneSeleniumContainer(SeleniumImage.STANDALONE_CHROME,
                                             DesiredCapabilities.CHROME)
        with chrome:
            driver = chrome.get_driver()
            driver.get("http://google.com")
            driver.find_element_by_name("q").send_keys("Hello")
----

=== Selenium Grid

It can spin up Selenium Grid Hub and Nodes for either Firefox or Chrome.
You can control number of nodes by setting constructor parameter `node_count`

[source,python]
----
    def test_selenium_grid(self):
        with SeleniumGrid(DesiredCapabilities.FIREFOX, node_count=3) as firefox:
            webdriver = firefox.get_driver()
            webdriver.get("http://google.com")
            webdriver.find_element_by_name("q").send_keys("Hello")
----

=== Database containers

You can spin up already implemented MySQL, MariaDB, PostgreSQL and Oracle-XE containers

==== MySQL:

[source,python]
----
    def test_docker_run_mysql():
    container = MySqlContainer("user", "secret", version="5.7")
    with container as mysql:
        e = sqlalchemy.create_engine(mysql.get_connection_url())
        result = e.execute("select version()")
        for row in result:
            assert row[0] == '5.7.14'
----

==== PostgreSQL:

[source,python]
----
    def test_docker_run_postgress():
        postgres_container = PostgresContainer("user", "secret", version="9.5")
        with postgres_container as postgres:
            conn = psycopg2.connect(host=postgres.host_ip,
                                    user=postgres.username,
                                    password=postgres.password,
                                    database=postgres.database)
            cur = conn.cursor()

            cur.execute("SELECT VERSION()")
            row = cur.fetchone()
            print("server version:", row[0])
            cur.close()
----

==== Generic database (ex. Mongo)

[source,python]
----
    def test_docker_generic_db():
    mongo_container = DockerContainer(image_name="mongo",
                                      version="latest",
                                      container_name="mongodb")
    mongo_container.bind_ports(27017, 27017)

    with mongo_container:
        @wait_container_is_ready()
        def connect():
            return MongoClient("mongodb://0.0.0.0:27017")

        db = connect().primer
        result = db.restaurants.insert_one(
            {
                "borough": "Manhattan",
                "cuisine": "Italian",
                "name": "Vella",
                "restaurant_id": "41704620"
            }
        )
        print(result.inserted_id)
        cursor = db.restaurants.find({"borough": "Manhattan"})
        for document in cursor:
            print(document)
----


Contribution
------------

Run tests:

    tox -epep8
    tox -epsphinx-docs
